# Generated by Django 2.1.3 on 2019-04-04 17:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zip', models.IntegerField()),
                ('town', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('housenumber', models.CharField(max_length=50)),
                ('information', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('sensor_no', models.IntegerField()),
                ('sensor_status', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_min', models.IntegerField(default=0)),
                ('shipment_cost', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Detailprice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Detail')),
            ],
        ),
        migrations.CreateModel(
            name='Orderbasket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('quantity', models.IntegerField(default=1)),
                ('confirmed', models.BooleanField(default=False)),
                ('ordered', models.BooleanField(default=False)),
                ('discount_abs', models.IntegerField(default=0)),
                ('discount_percent', models.IntegerField(default=0)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.Address')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Detail')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ordernumber', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('delivered', models.BooleanField(default=False)),
                ('delivery_number', models.CharField(default='notset', max_length=50)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Orderbasket')),
            ],
        ),
        migrations.CreateModel(
            name='Pricelist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('shipment_cost', models.IntegerField(default=0)),
                ('order_min_value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliercontract',
            fields=[
                ('Suppliercontract_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='detailprice',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Pricelist'),
        ),
        migrations.AddField(
            model_name='detail',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Pricelist'),
        ),
        migrations.AddField(
            model_name='detail',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Supplier'),
        ),
        migrations.AddField(
            model_name='article',
            name='supplier',
            field=models.ManyToManyField(through='warehouse.Detail', to='warehouse.Supplier'),
        ),
    ]
