# Generated by Django 2.1.3 on 2018-12-09 11:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('sensor_no', models.IntegerField()),
                ('sensor_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shipment_cost', models.IntegerField(default=0)),
                ('order_min', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Orderbasket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Detail')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliercontract',
            fields=[
                ('Suppliercontract_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='detail',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Supplier'),
        ),
        migrations.AddField(
            model_name='article',
            name='supplier',
            field=models.ManyToManyField(through='warehouse.Detail', to='warehouse.Supplier'),
        ),
    ]
