# Generated by Django 2.1.3 on 2019-04-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_remove_detail_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailprice',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
