# Generated by Django 2.1.3 on 2018-12-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_orderbasket_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbasket',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
