# Generated by Django 2.1.3 on 2019-01-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_orderbasket_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbasket',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
