# Generated by Django 2.1.3 on 2019-01-27 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_orderbasket_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ordernumber', models.CharField(max_length=50, unique=True)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Orderbasket')),
            ],
        ),
    ]
