# Generated by Django 2.1.3 on 2019-02-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='ordernumber',
            field=models.CharField(max_length=50),
        ),
    ]
