# Generated by Django 2.1.3 on 2019-02-17 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_auto_20190217_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
