# Generated by Django 2.1.3 on 2019-02-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_orders_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zip', models.IntegerField()),
                ('town', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('housenumber', models.CharField(max_length=50)),
                ('information', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='orderbasket',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_number',
            field=models.CharField(default='notset', max_length=50),
        ),
        migrations.AddField(
            model_name='supplier',
            name='order_min_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='shipment_cost',
            field=models.IntegerField(default=0),
        ),
    ]
