# Generated by Django 2.1.3 on 2019-02-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_auto_20190224_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbasket',
            name='discount_abs',
        ),
        migrations.RemoveField(
            model_name='orderbasket',
            name='discount_percent',
        ),
        migrations.AddField(
            model_name='orders',
            name='discount_abs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='discount_percent',
            field=models.IntegerField(default=0),
        ),
    ]
