# Generated by Django 2.1.3 on 2019-02-24 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_orders_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='discount_abs',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='discount_percent',
        ),
        migrations.AddField(
            model_name='orderbasket',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.Address'),
        ),
        migrations.AddField(
            model_name='orderbasket',
            name='discount_abs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderbasket',
            name='discount_percent',
            field=models.IntegerField(default=0),
        ),
    ]
