# Generated by Django 2.1.3 on 2019-02-24 18:31

from django.db import migrations, models
import warehouse.models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_auto_20190224_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=warehouse.models.get_image_path),
        ),
    ]
