# Generated by Django 2.1.3 on 2019-03-02 09:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0016_auto_20190228_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detailprice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='detail',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Detailprice'),
        ),
    ]
