# Generated by Django 2.1.3 on 2019-03-02 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0017_auto_20190302_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detailprice',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Detail'),
        ),
    ]
