# Generated by Django 2.1.3 on 2019-03-02 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0018_auto_20190302_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Detailprice'),
        ),
        migrations.AlterField(
            model_name='detailprice',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
