# Generated by Django 2.1.3 on 2019-03-02 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0019_auto_20190302_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.Detailprice'),
        ),
    ]
