# Generated by Django 2.1.3 on 2019-03-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0025_detail_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='date',
        ),
        migrations.AddField(
            model_name='detail',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
